#!/bin/bash
set -euo pipefail

# ALEA Intake - Self-Hosted Installation Script
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/alea/alea-intake/main/scripts/install.sh | bash
#
# Or clone and run locally:
#   ./scripts/install.sh

ALEA_VERSION="${ALEA_VERSION:-1.0.0}"
COMPOSE_URL="https://raw.githubusercontent.com/alea/alea-intake/v${ALEA_VERSION}/docker-compose.yml"
INSTALL_DIR="${ALEA_INSTALL_DIR:-./alea-intake}"

# ── Banner ──────────────────────────────────────────────────────────
echo ""
echo "  ╔═══════════════════════════════════════════╗"
echo "  ║   ALEA Intake - Self-Hosted Setup         ║"
echo "  ║   AI-powered legal intake system          ║"
echo "  ║   Version: ${ALEA_VERSION}                          ║"
echo "  ╚═══════════════════════════════════════════╝"
echo ""

# ── Prerequisites ───────────────────────────────────────────────────
check_prereq() {
  if ! command -v "$1" &>/dev/null; then
    echo "ERROR: $1 is required but not installed."
    echo "Install $1 and try again."
    exit 1
  fi
}

check_prereq docker

# Check for docker compose (v2 plugin)
if ! docker compose version &>/dev/null; then
  echo "ERROR: 'docker compose' (v2) is required."
  echo "Install Docker Compose v2: https://docs.docker.com/compose/install/"
  exit 1
fi

echo "[1/5] Prerequisites verified: docker, docker compose"

# ── Installation directory ──────────────────────────────────────────
mkdir -p "${INSTALL_DIR}"
cd "${INSTALL_DIR}"

echo "[2/5] Created installation directory: ${INSTALL_DIR}"

# ── Generate secrets ────────────────────────────────────────────────
generate_secret() {
  # Generate a 32-byte random hex string
  if command -v openssl &>/dev/null; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | xxd -p -c 64 2>/dev/null || \
      python3 -c "import secrets; print(secrets.token_hex(32))"
  fi
}

SECRET_KEY=$(generate_secret)
MASTER_KEY=$(generate_secret)

echo "[3/5] Generated cryptographic secrets"

# ── Download docker-compose.yml ─────────────────────────────────────
if [ -f "../docker-compose.yml" ] && [ -f "../Dockerfile" ]; then
  # Local development: copy from parent
  cp ../docker-compose.yml ./docker-compose.yml
  echo "[4/5] Copied docker-compose.yml from local source"
else
  echo "Downloading docker-compose.yml..."
  curl -fsSL "${COMPOSE_URL}" -o docker-compose.yml
  echo "[4/5] Downloaded docker-compose.yml"
fi

# ── Create .env with generated secrets ──────────────────────────────
cat > .env <<ENVFILE
# ALEA Intake Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

ALEA_SECRET_KEY=${SECRET_KEY}
ALEA_MASTER_KEY=${MASTER_KEY}
ENVFILE

# ── Create data directory ───────────────────────────────────────────
mkdir -p data

# ── Start services ──────────────────────────────────────────────────
echo "[5/5] Starting ALEA Intake..."
docker compose up -d

echo ""
echo "  ============================================"
echo "  ALEA Intake is starting up!"
echo ""
echo "  Access:  http://localhost:8000"
echo "  Health:  http://localhost:8000/health"
echo "  Docs:    http://localhost:8000/docs"
echo ""
echo "  Data stored in: ${INSTALL_DIR}/data/"
echo "  Config:  ${INSTALL_DIR}/.env"
echo ""
echo "  First login:"
echo "    Create an admin account via the API or"
echo "    check the docs at /docs for setup steps."
echo ""
echo "  To stop:  cd ${INSTALL_DIR} && docker compose down"
echo "  To update: docker compose pull && docker compose up -d"
echo "  ============================================"
echo ""
